blueprint:
  name: Presence Lighting
  description: >
    Turns lights on and off based on room presence. Supports customizable
    turn-on/off actions, alternate delays (for guests or nighttime), sleeping
    child suppression, upstairs lighting timer checks, and arbitrary custom
    conditions via templates.

    Note: Lights will never turn on for a room whose presence state is
    sleeping (Going to Sleep, Sleeping, Waking Up), because the turn-on
    branch requires a transition from an unoccupied state (Empty, Extended
    Away, Unknown) to an occupied state. Sleeping states are not unoccupied,
    so they cannot produce that transition.
  domain: automation
  input:
    # ========== Room Setup ==========
    room_presence_entity:
      name: Room presence entity
      description: >
        The input_select entity that tracks room presence
        (e.g., input_select.presence_garage).
      selector:
        entity:
          domain: input_select

    light_entity_to_check:
      name: Primary light entity to check
      description: >
        The main light entity for this room. The turn-on branch checks this is
        "off" before turning on, and the turn-off branch checks it is "on" before
        turning off. Leave empty to skip the state check (useful for rooms with
        complex multi-light logic handled in custom actions/conditions).
      default: ""
      selector:
        entity:
          domain: light

    # ========== Turn-On ==========
    turn_on_actions:
      name: Turn-on actions
      description: >
        Actions to execute when turning the light on. Can be as simple as
        calling a script (e.g., script.lighting_garage_on) or as complex as
        a multi-step sequence with choose/if blocks for theater mode, brightness
        levels, etc. The variable "is_upstairs_timer_active" is available here.
      selector:
        action: {}

    additional_on_triggers:
      name: Additional scenarios where lights should turn on
      description: >
        Optional extra triggers that cause lights to turn on (e.g., a motion
        sensor or door contact). These are given trigger ID "sensor_detected"
        so the blueprint routes them to the turn-on branch.
      default: []
      selector:
        trigger: {}

    additional_on_condition:
      name: Additional turn-on conditions
      description: >
        Extra conditions that must be met for the light to turn on. Use the
        HA condition editor to add state checks, template conditions, time
        ranges, etc. Leave empty (default) to skip.

        The blueprint already checks these before turn-on:
        - Global toggles are on (presence, lighting, vacation mode off)
        - Room transitioned from empty/away to occupied
        - House is not in sleep mode (if "Block turn-on when the house is sleeping" is enabled)
        - Primary light is currently off (if a light entity is set)
        - Sleeping child suppression is not active (if that flag is enabled)

        Use this input for room-specific logic not covered above, such as
        theater mode, dinner party mode, or checking nearby room lights.
      default: []
      selector:
        condition: {}

    check_room_not_sleeping:
      name: Block turn-on when the house is sleeping
      description: >
        When enabled, prevents lights from turning on if
        input_boolean.sleep_mode is on. Disable this for rooms like Kitchen
        that should turn on at low brightness during sleep instead of
        blocking entirely.

        Note: Even with this disabled, lights never turn on for a room
        whose presence state is sleeping (Going to Sleep, Sleeping, Waking
        Up) because the blueprint requires a transition from an unoccupied
        state to trigger the turn-on branch.
      default: false
      selector:
        boolean: {}

    check_suppress_sleeping_child:
      name: Check suppress lights for sleeping child
      description: >
        When enabled, the turn-on branch will only fire if
        input_boolean.suppress_lights_for_sleeping_child is off.
      default: false
      selector:
        boolean: {}

    check_upstairs_timer:
      name: Check upstairs lighting timer
      description: >
        When enabled, the variable "is_upstairs_timer_active" is set based on
        timer.briefly_minimize_upstairs_lighting. Reference this variable in
        your turn-on actions to adjust brightness or skip turning on.
      default: false
      selector:
        boolean: {}

    # ========== Turn-Off ==========
    turn_off_actions:
      name: Turn-off actions
      description: >
        Actions to execute when turning the light off (after the delay). Can
        include script calls, fan turn-offs, inline light.turn_off, etc.
      selector:
        action: {}

    additional_off_triggers:
      name: Additional scenarios where lights should turn off
      description: >
        Optional extra triggers that cause lights to turn off (e.g., a motion
        sensor clearing). These are given trigger ID "sensor_cleared" so the
        blueprint routes them to the turn-off branch.
      default: []
      selector:
        trigger: {}

    additional_off_condition:
      name: Additional turn-off conditions
      description: >
        Extra conditions that must be met for the light to turn off. Use the
        HA condition editor to add state checks, template conditions, etc.
        Leave empty (default) to skip.

        The blueprint already checks these before turn-off:
        - Global toggles are on (presence, lighting, vacation mode off)
        - Room is in an unoccupied state (Unknown, Extended Away, or Empty)
        - Primary light is currently on (if a light entity is set)

        Use this input for room-specific logic not covered above, such as
        dinner party mode or area occupancy sensors.
      default: []
      selector:
        condition: {}

    delay_before_off:
      name: Delay before off (minutes)
      description: >
        Minutes to wait after the room becomes unoccupied before turning off
        the lights.
      default: 0
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes
          mode: box

    alternate_delay_condition:
      name: Alternate delay condition
      description: >
        Conditions that, when met, cause the alternate delay to be used
        instead of the normal delay. Use the HA condition editor to add
        state checks, template conditions, etc. Leave empty (default) to
        always use the normal delay.
        Examples: guest mode is on, sleep mode is on, time is after 11pm.
      default: []
      selector:
        condition: {}

    alternate_delay:
      name: Alternate delay (minutes)
      description: >
        A second delay value used when the alternate delay condition above
        is met. Set to 0 for instant off.
      default: 0
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes
          mode: box

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input room_presence_entity
    id: room_presence_changes
    alias: Room presence changes
  - triggers: !input additional_on_triggers
    id: sensor_detected
  - triggers: !input additional_off_triggers
    id: sensor_cleared

conditions:
  - condition: state
    entity_id: input_boolean.presence_enable_automations
    state: "on"
  - condition: state
    entity_id: input_boolean.enable_lighting_automations
    state: "on"
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: "off"

actions:
  - variables:
      room_presence_entity_id: !input room_presence_entity
      delay_before_off_val: !input delay_before_off
      alternate_delay_val: !input alternate_delay
      light_check: !input light_entity_to_check
      suppress_sleeping: !input check_suppress_sleeping_child
      upstairs_timer: !input check_upstairs_timer
      check_not_sleeping: !input check_room_not_sleeping
      unoccupied_states:
        - Unknown
        - Extended Away
        - Empty
      sleeping_states:
        - Going to Sleep
        - Sleeping
        - Waking Up
      room_presence_state: "{{ states(room_presence_entity_id) }}"
      triggered_by_a_room: >-
        {{ trigger.entity_id.startswith('input_select.presence_') }}
      triggered_by_current_room: >-
        {{ trigger.entity_id == room_presence_entity_id }}
      is_room_state_trigger_empty_to_occupied: >-
        {% if triggered_by_a_room %}
          {% set current_state = trigger.to_state.state %}
          {% set previous_state = trigger.from_state.state %}
          {% if current_state not in unoccupied_states and previous_state in unoccupied_states %}
            true
          {% else %}
            false
          {% endif %}
        {% else %}
          true
        {% endif %}
      is_upstairs_timer_active: >-
        {% if upstairs_timer %}
          {{ is_state('timer.briefly_minimize_upstairs_lighting', 'active') }}
        {% else %}
          false
        {% endif %}
    alias: Define room presence variables

  - choose:
    - conditions:
      - condition: trigger
        id:
          - room_presence_changes
          - sensor_detected
      - condition: template
        value_template: "{{ is_room_state_trigger_empty_to_occupied }}"
        alias: Room transitioned from empty to occupied
      - condition: template
        value_template: >-
          {% if check_not_sleeping %}
            {{ is_state('input_boolean.sleep_mode', 'off') }}
          {% else %}
            true
          {% endif %}
        alias: House is not in sleep mode (if enabled)
      - condition: template
        value_template: >-
          {{ not light_check or is_state(light_check, 'off') }}
        alias: Primary light is off (or check skipped)
      - condition: template
        value_template: >-
          {% if suppress_sleeping %}
            {{ is_state('input_boolean.suppress_lights_for_sleeping_child', 'off') }}
          {% else %}
            true
          {% endif %}
        alias: Suppress lights for sleeping child (if enabled)
      - alias: Additional turn-on conditions
        condition: and
        conditions: !input additional_on_condition
      sequence: !input turn_on_actions
      alias: Turn the light on

    - conditions:
      - condition: trigger
        id:
          - room_presence_changes
          - sensor_cleared
      - condition: template
        value_template: "{{ room_presence_state in unoccupied_states }}"
        alias: Room is unoccupied
      - condition: template
        value_template: >-
          {{ not light_check or is_state(light_check, 'on') }}
        alias: Primary light is on (or check skipped)
      - alias: Additional turn-off conditions
        condition: and
        conditions: !input additional_off_condition
      sequence:
      - choose:
        - alias: Use alternate delay
          conditions: !input alternate_delay_condition
          sequence:
            - delay:
                hours: 0
                minutes: !input alternate_delay
                seconds: 0
              alias: Alternate delay before turning off
        default:
          - delay:
              hours: 0
              minutes: !input delay_before_off
              seconds: 0
            alias: Normal delay before turning off
      - choose: []
        default: !input turn_off_actions
      alias: Turn the light off after a delay
    alias: Turn on or off the lights
