blueprint:
  name: Presence Lighting
  description: >
    Turns lights on and off based on room presence or another entity. Supports running any action, custom conditions, and custom delays based on a condition. Turn-on always first confirms that the room is not already occupied or sleeping. Also supports optional conditions for minimizing upstairs lighting or suppressing lighting when a child is sleeping.
  domain: automation
  input:
    # ========== Room Setup ==========
    room_presence_entity:
      name: Room presence entity
      description: >
        The input_select entity that tracks room presence.
      selector:
        entity:
          domain: input_select

    room_presence_trigger_mode:
      name: Use room presence for lighting
      description: >
        Controls whether the lights should turn on and off with room presence.
      default: both
      selector:
        select:
          options:
            - label: Occupancy and vacancy
              value: both
            - label: Occupancy only
              value: detect_only
            - label: Vanancy only
              value: clear_only
            - label: Ignore room presence
              value: neither

    light_entity_to_check:
      name: Primary light
      description: >
        Confirm this light is off before turning it on or vice versa. Leave empty to skip this check (useful for rooms with complex multi-light logic handled in additional conditions).
      default: ""
      selector:
        entity:
          domain: light

    # ========== Turn-On ==========
    additional_detect_entities:
      name: Additional turn-on entities
      description: >
        Additional entities that should turn on the light when they 
        transition from off to on. 

        If no entities are selected, the default (sun.sun) is required
        to ensure the blueprint works.
      default:
        - sun.sun
      selector:
        entity:
          multiple: true

    additional_on_condition:
      name: Additional turn-on conditions
      description: >
        Extra conditions that must be met for the light to turn on.

        The blueprint has built-in checks for the following:
        - Presence and lighting automations are enabled
        - Vacation mode is off
        - The room state is not sleeping
        - The light is currently off (if a light entity is set above)
        - Additional turn-on toggles below
      default: []
      selector:
        condition: {}

    require_room_unoccupied_for_sensors:
      name: Confirm room is unoccupied
      description: >
        Before turning on the light, ensure the room is unoccupied (prevents room state changes from turning the light back on when users want it off).
      default: true
      selector:
        boolean: {}

    suppress_when_upstairs_minimized:
      name: Confirm upstairs lighting isn't minimized
      description: >
        Before turning on the light, ensure minimize upstairs lighting isn't enabled.
      default: false
      selector:
        boolean: {}

    check_suppress_sleeping_child:
      name: Confirm lighting isn't suppressed for a sleeping child
      description: >
        Before turning on the light, ensure suppress lights for sleeping child isn't enabled (avoids turning on the lights when arriving home with a sleeping child.
      default: false
      selector:
        boolean: {}

    turn_on_actions:
      name: Turn-on actions
      description: >
        Actions to take when the light should turn on.
      selector:
        action: {}

    # ========== Turn-Off ==========
    additional_clear_entities:
      name: Additional turn-off entities
      description: >
        Additional entities that should turn off the light when they 
        transition from on to off. 

        If no entities are selected, the default (sun.sun) is required
        to ensure the blueprint works.
      default:
        - sun.sun
      selector:
        entity:
          multiple: true

    additional_off_condition:
      name: Additional turn-off conditions
      description: >
        Extra conditions that must be met for the light to turn off.

        The blueprint has built-in checks for the following:
        - Presence and lighting automations are enabled
        - Vacation mode is off
        - The light is currently on (if a light entity is set above)
      default: []
      selector:
        condition: {}

    delay_before_off:
      name: Delay before off (minutes)
      description: >
        How long to wait before turning off the lights.
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 0.1
          unit_of_measurement: minutes
          mode: box

    alternate_delay_condition:
      name: Alternate delay condition
      description: >
        Override the default delay when these conditions are met. Useful for scenarios like waiting longer to turn off the lights when a guest is visiting.
      default: []
      selector:
        condition: {}

    alternate_delay:
      name: Alternate delay (minutes)
      description: >
        How long to wait before turning off the lights if the alternate delay condition is met.
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 0.1
          unit_of_measurement: minutes
          mode: box

    turn_off_actions:
      name: Turn-off actions
      description: >
        Actions to take when the light should turn off.
      selector:
        action: {}

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input room_presence_entity
    id: room_presence_changes
    alias: Room presence changes
  - trigger: state
    entity_id: !input additional_detect_entities
    from: "off"
    to: "on"
    id: sensor_detected
    alias: Additional detect entity activated
  - trigger: state
    entity_id: !input additional_clear_entities
    from: "on"
    to: "off"
    id: sensor_cleared
    alias: Additional clear entity deactivated

conditions:
  - condition: state
    entity_id: input_boolean.presence_enable_automations
    state: "on"
  - condition: state
    entity_id: input_boolean.enable_lighting_automations
    state: "on"
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: "off"

actions:
  - variables:
      room_presence_entity_id: !input room_presence_entity
      delay_before_off_val: !input delay_before_off
      alternate_delay_val: !input alternate_delay
      light_check: !input light_entity_to_check
      suppress_sleeping: !input check_suppress_sleeping_child
      suppress_upstairs: !input suppress_when_upstairs_minimized
      rp_mode: !input room_presence_trigger_mode
      require_unoccupied_for_sensors: !input require_room_unoccupied_for_sensors
      unoccupied_states:
        - Unknown
        - Extended Away
        - Empty
      sleeping_states:
        - Going to Sleep
        - Sleeping
        - Waking Up
      room_presence_state: "{{ states(room_presence_entity_id) }}"
      triggered_by_a_room: >-
        {{ trigger.entity_id.startswith('input_select.presence_') }}
      is_room_state_trigger_empty_to_occupied: >-
        {% if triggered_by_a_room %}
          {% set current_state = trigger.to_state.state %}
          {% set previous_state = trigger.from_state.state %}
          {% if current_state not in unoccupied_states and previous_state in unoccupied_states %}
            true
          {% else %}
            false
          {% endif %}
        {% else %}
          {% if require_unoccupied_for_sensors %}
            {{ states(room_presence_entity_id) in unoccupied_states }}
          {% else %}
            true
          {% endif %}
        {% endif %}
    alias: Define room presence variables

  - choose:
    - conditions:
      - condition: template
        value_template: >-
          {% if trigger.id == 'sensor_detected' %}
            true
          {% elif trigger.id == 'room_presence_changes' %}
            {{ rp_mode in ['both', 'detect_only'] }}
          {% else %}
            false
          {% endif %}
        alias: Trigger is a detect entity or room presence (if mode allows)
      - condition: template
        value_template: "{{ is_room_state_trigger_empty_to_occupied }}"
        alias: Room transitioned from empty to occupied
      - condition: template
        value_template: >-
          {{ states(room_presence_entity_id) not in sleeping_states }}
        alias: Room is not in a sleeping state
      - condition: template
        value_template: >-
          {{ not light_check or is_state(light_check, 'off') }}
        alias: Primary light is off (or check skipped)
      - condition: template
        value_template: >-
          {% if suppress_sleeping %}
            {{ is_state('input_boolean.suppress_lights_for_sleeping_child', 'off') }}
          {% else %}
            true
          {% endif %}
        alias: Suppress lights for sleeping child (if enabled)
      - condition: template
        value_template: >-
          {% if suppress_upstairs %}
            {{ not is_state('timer.briefly_minimize_upstairs_lighting', 'active') }}
          {% else %}
            true
          {% endif %}
        alias: Suppress turn-on when upstairs lighting is minimized (if enabled)
      - alias: Additional turn-on conditions
        condition: and
        conditions: !input additional_on_condition
      sequence: !input turn_on_actions
      alias: Turn the light on

    - conditions:
      - condition: template
        value_template: >-
          {% if trigger.id == 'sensor_cleared' %}
            true
          {% elif trigger.id == 'room_presence_changes' %}
            {{ rp_mode in ['both', 'clear_only'] }}
          {% else %}
            false
          {% endif %}
        alias: Trigger is a clear entity or room presence (if mode allows)
      - condition: template
        value_template: "{{ room_presence_state in unoccupied_states }}"
        alias: Room is unoccupied
      - condition: template
        value_template: >-
          {{ not light_check or is_state(light_check, 'on') }}
        alias: Primary light is on (or check skipped)
      - alias: Additional turn-off conditions
        condition: and
        conditions: !input additional_off_condition
      sequence:
      - choose:
        - alias: Use alternate delay
          conditions:
            - condition: or
              conditions: !input alternate_delay_condition
          sequence:
            - delay:
                hours: 0
                minutes: !input alternate_delay
                seconds: 0
              alias: Alternate delay before turning off
        default:
          - delay:
              hours: 0
              minutes: !input delay_before_off
              seconds: 0
            alias: Normal delay before turning off
      - choose: []
        default: !input turn_off_actions
      alias: Turn the light off after a delay
    alias: Turn on or off the lights
